version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: curso
        MYSQL_USER: usuario
        MYSQL_PASSWORD: password
    volumes:
        - /home/ubuntu/environment/datos:/var/lib/mysql
    ports:
      - 3307:3006

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080